# Plotting Map using Folium

In [2]:
import numpy as np
import pandas as pd
import folium
from folium import plugins

In [6]:
world_map = folium.Map(tiles='Cartodb positron')
world_map

In [8]:
df_crime = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Police_Department_Incidents_-_Previous_Year__2016_.csv')
df_crime.head()

,IncidntNum,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,Address,X,Y,Location,PdId
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212120
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",Friday,01/29/2016 12:00:00 AM,11:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,-122.403405,37.775421,"(37.775420706711, -122.403404791479)",12005827212168
2,141059263,WARRANTS,WARRANT ARREST,Monday,04/25/2016 12:00:00 AM,14:59,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,-122.388856,37.729981,"(37.7299809672996, -122.388856204292)",14105926363010
3,160013662,NON-CRIMINAL,LOST PROPERTY,Tuesday,01/05/2016 12:00:00 AM,23:50,TENDERLOIN,NONE,JONES ST / OFARRELL ST,-122.412971,37.785788,"(37.7857883766888, -122.412970537591)",16001366271000
4,160002740,NON-CRIMINAL,LOST PROPERTY,Friday,01/01/2016 12:00:00 AM,00:30,MISSION,NONE,16TH ST / MISSION ST,-122.419672,37.765050,"(37.7650501214668, -122.419671780296)",16000274071000

In [9]:
print(df_crime.shape)
df_crime = df_crime.iloc[0:200, :]

(150500, 13)

In [15]:
sanfran_map = folium.Map(location=[37.77, -122.42], zoom_start=12)

crimes = folium.map.FeatureGroup()
for lat, lng, in zip(df_crime.Y, df_crime.X):
    crimes.add_child(
        folium.vector_layers.CircleMarker(
            [lat, lng], radius=5, color='red', fill=True, fill_color='white', fill_opacity=0.8))

sanfran_map.add_child(crimes)

In [25]:
sanfran_map = folium.Map(location=[37.77, -122.42], zoom_start=12)

crimes = folium.map.FeatureGroup()

for lat, lng, in zip(df_crime.Y, df_crime.X):
    crimes.add_child(folium.vector_layers.CircleMarker(
    [lat, lng], radius=5, color='yellow', fill_color='blue', fill_opacity=0.6))

latitudes = list(df_crime.Y)
longitudes = list(df_crime.X)
labels = list(df_crime.Category)

for lat, lng, label in zip(latitudes, longitudes, labels):
    folium.Marker([lat, lng], icon=folium.Icon(icon='info_icon', color='lightblue'), popup=label).add_to(sanfran_map)    
    
sanfran_map.add_child(crimes)

In [23]:
sanfran_map = folium.Map(location=[37.77, -122.42], zoom_start=12)

for lat, lng, label in zip(df_crime.Y, df_crime.X, df_crime.Category):
    folium.vector_layers.CircleMarker(
    [lat, lng], popup=label, radius=5, color='yellow', fill_color='blue', fill_opacity=0.6).add_to(sanfran_map)
   
sanfran_map

In [29]:
sanfran_map = folium.Map(location = [37.77, -122.42], zoom_start = 12)

c = plugins.MarkerCluster().add_to(sanfran_map)

for lat, lng, label, in zip(df_crime.Y, df_crime.X, df_crime.Category):
    folium.Marker(location=[lat, lng], icon=None, popup=label).add_to(c)

sanfran_map

In [31]:
df_can = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.csv')
df_can.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [35]:
world_geo = r'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/world_countries.json'

world_map = folium.Map(location=[0, 0], zoom_start=2)
folium.Choropleth(
    geo_data=world_geo,
    data=df_can,
    columns=['Country', 'Total'],
    key_on='feature.properties.name',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    legend_name='Immigration to Canada'
).add_to(world_map)

world_map